### ISSUE TITLE
Script used to create the triplet list

### ISSUE THREAD

**Issue by hmishfaq** [andreasveit/conditional-similarity-networks#5]
Is it possible to share the script that has been used to create the triplet list?

Thanks
Haque

**Comment by theFool32** [comment]
Need it as well.
Does it simply sample triplet from the database or use any trick?

Thanks.

**Comment by andreasveit** [comment]
We simply sample triplets randomly from the database. The procedure is outlined in the paper as well:

> To supervise and evaluate the triplet networks, we sample triplet constraints from the annotations of the datasets. For the font dataset, we sample triplets such that two characters are of the same type or font and one is different. For the Zappos dataset, we sample triplets in an analogous way for the three categorical attributes. For the heel heights we have numerical measurements so that for each triplet we pick two shoes with similar height and one with different height.
