### ISSUE TITLE
embedding vector is not same everytime

### ISSUE THREAD

**Issue by sandeeprepakula** [andreasveit/conditional-similarity-networks#7]
Hi,

I am trying to retrieve the embedding vector for a given image once the model is trained. I am getting different embedded vectors for different instances of the same image. 

Is the embedding returned a deterministic one?

**Comment by andreasveit** [comment]
Thank you for your interest in this project.
Are you sure that the model is in inference (eval) mode while extracting the embedding vectors?

**Comment by sandeeprepakula** [comment]
Yes. 

But I made a mistake in applying transoformations. There was some randomisation involved during one of the steps of the transformations. After fixing this, the vectors are same across multiple runs. Hence closing the issue.

Thanks.
